language: go

go:
  - tip

before_install:
  - go get github.com/coreos/etcd
  - go get golang.org/x/net/context
  - go get github.com/gin-gonic/gin

script:
  go test `go list ./... | grep -v tests`
