# Deploys an ETCD server in cluster
# NOTE: It can be installed as a server but it seems to not work properly with Docker
- hosts: etcd
  become: yes
  become_method: sudo
  vars:
    etcd_server: 192.168.1.35

  tasks:
    - name: Add ETCD
      yum: name=docker state=present

    - name: Start ETCD
      shell: "nohup etcd -listen-client-urls 'http://{{ etcd_server }}:2379' -advertise-client-urls 'http://{{ etcd_server }}:2379' &"
